# Generated by Django 4.2.5 on 2023-11-18 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('required_caregiving_type', models.CharField(max_length=50)),
                ('other_requirements', models.TextField()),
                ('date_posted', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('given_name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('profile_description', models.TextField()),
                ('_password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Caregiver',
            fields=[
                ('caregiver_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='caregivers.user')),
                ('photo', models.BinaryField()),
                ('gender', models.CharField(max_length=10)),
                ('caregiving_type', models.CharField(choices=[('babysitter', 'Babysitter'), ('caregiver_for_elderly', 'Caregiver for Elderly'), ('playmate_for_children', 'Playmate for Children')], max_length=50)),
                ('hourly_rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='caregivers.user')),
                ('house_rules', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('member_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='caregivers.member')),
                ('house_number', models.CharField(max_length=10)),
                ('street', models.CharField(max_length=255)),
                ('town', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_applied', models.DateField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caregivers.job')),
                ('caregiver_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caregivers.caregiver')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='member_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caregivers.member'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('work_hours', models.IntegerField()),
                ('_status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Pending', 'Pending')], max_length=50)),
                ('caregiver_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caregivers.caregiver')),
                ('member_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caregivers.member')),
            ],
        ),
    ]
