# Generated by Django 4.2.5 on 2023-11-19 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caregivers', '0002_remove_caregiver_photo_caregiver_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='_password',
        ),
    ]
