# Generated by Django 4.2.5 on 2023-11-20 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caregivers', '0004_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caregiver',
            name='caregiver_user',
        ),
        migrations.RemoveField(
            model_name='member',
            name='member_user',
        ),
        migrations.AddField(
            model_name='caregiver',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='caregivers.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='caregivers.user'),
            preserve_default=False,
        ),
    ]
