# Generated by Django 4.2.5 on 2023-11-20 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caregivers', '0005_remove_caregiver_caregiver_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caregiver',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='member',
            name='user_ptr',
        ),
        migrations.AddField(
            model_name='caregiver',
            name='caregiver_user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='caregivers.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='member_user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='caregivers.user'),
            preserve_default=False,
        ),
    ]
