# Generated by Django 4.2.5 on 2023-11-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caregivers', '0007_user_is_active_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('member', 'Member'), ('caregiver', 'Caregiver')], default=0, max_length=50),
            preserve_default=False,
        ),
    ]
