# Generated by Django 4.2.5 on 2023-11-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caregivers', '0011_rename__status_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('PENDING', 'Pending'), ('CANCELLED', 'Cancelled')], max_length=50),
        ),
    ]
